language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "eletterbank-github"
    token:
      secure: "5b35f1d3ed234a627cfdaa0a5183778bc439b03d"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
